### ISSUE TITLE
bad input file causes segfault

### ISSUE THREAD

**Issue by garlick** [cktan/tomlc99#3]
I wrote a little TAP test suite for a project that is importing tomlc99.  It attempts to parse the BurntSushi invalid and valid input files.  I ran across one input file that caused a segfault.  It is `table-array-implicit.toml` and looks like this:

```toml
# This test is a bit tricky. It should fail because the first use of
# `[[albums.songs]]` without first declaring `albums` implies that `albums`
# must be a table. The alternative would be quite weird. Namely, it wouldn't
# comply with the TOML spec: "Each double-bracketed sub-table will belong to 
# the most *recently* defined table element *above* it."
#
# This is in contrast to the *valid* test, table-array-implicit where
# `[[albums.songs]]` works by itself, so long as `[[albums]]` isn't declared
# later. (Although, `[albums]` could be.)
[[albums.songs]]
name = "Glory Days"

[[albums]]
name = "Born in the USA"
```

Here's a backtrace from gdb
```
Program received signal SIGSEGV, Segmentation fault.
parse_select (ctx=0x7fffffffd120) at toml.c:1143
1143		if (arr->kind == 0) arr->kind = 't';
(gdb) bt full
#0  parse_select (ctx=0x7fffffffd120) at toml.c:1143
        arr = 0x0
        dest = <optimized out>
        count_lbracket = 2
        z = {tok = <optimized out>, lineno = 13, 
          ptr = 0x60bf5c "albums]]\nname = \"Born in the USA\"\n", len = 6, 
          eof = <optimized out>}
#1  toml_parse (
    conf=conf@entry=0x60bd10 "# This test is a bit tricky. It should fail because the first use of\n# `[[albums.songs]]` without first declaring `albums` implies that `albums`\n# must be a table. The alternative would be quite weird"..., 
    errbuf=errbuf@entry=0x7fffffffd4a0 "", errbufsz=errbufsz@entry=255)
    at toml.c:1258
        tok = {tok = <optimized out>, lineno = <optimized out>, 
          ptr = <optimized out>, len = <optimized out>, eof = 0}
        ctx = {
          start = 0x60bd10 "# This test is a bit tricky. It should fail because the first use of\n# `[[albums.songs]]` without first declaring `albums` implies that `albums`\n# must be a table. The alternative would be quite weird"..., 
          stop = 0x60bf7e "", errbuf = 0x7fffffffd4a0 "", errbufsz = 255, 
          jmp = {{__jmpbuf = {140737488343328, 7620089810268263470, 
                140737488344224, 255, 3001, 6339856, -7620090080383921106, 
                7620089533462025262}, __mask_was_saved = 0, __saved_mask = {
                __val = {0 <repeats 16 times>}}}}, tok = {tok = RBRACKET, 
            lineno = 13, ptr = 0x60bf62 "]]\nname = \"Born in the USA\"\n", 
            len = 1, eof = 0}, root = 0x60a010, curtab = 0x60a010, tpath = {
            top = 0, key = {0x612790 "", 0x6127b0 "P\242`", 0x0, 0x0, 0x0, 
              0x0, 0x0, 0x0, 0x0, 0x0}, tok = {{tok = STRING, lineno = 13, 
                ptr = 0x60bf5c "albums]]\nname = \"Born in the USA\"\n", 
                len = 6, eof = 0}, {tok = STRING, lineno = 10, 
                ptr = 0x60bf3d "songs]]\nname = \"Glory Days\"\n\n[[albums]]\nname = \"Born in the USA\"\n", len = 5, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}, {tok = INVALID, lineno = 0, 
                ptr = 0x0, len = 0, eof = 0}}}}
#2  0x0000000000404b4f in toml_parse_file (fp=fp@entry=0x60ae80, 
    errbuf=errbuf@entry=0x7fffffffd4a0 "", errbufsz=errbufsz@entry=255)
    at toml.c:1316
        bufsz = 2000
        buf = 0x60bd10 "# This test is a bit tricky. It should fail because the first use of\n# `[[albums.songs]]` without first declaring `albums` implies that `albums`\n# must be a table. The alternative would be quite weird"...
        off = 622
        ret = <optimized out>
#3  0x0000000000401698 in parse_bad_file (path=<optimized out>, 
    errbuf=0x7fffffffd4a0 "", errsize=255) at toml_tap.c:99
        fp = 0x60ae80
        conf = 0x0
#4  0x000000000040185a in parse_bad_input () at toml_tap.c:156
        errbuf = "\000ine 1: unterminated quote\000key", '\000' <repeats 224 times>
        name = 0x60a06b "table-array-implicit.toml"
        reason = 0x406702 "parses"
        blacklisted = <optimized out>
        pattern = "./BurntSushi_input/invalid/*.toml", '\000' <repeats 1127 times>...
        results = {gl_pathc = 40, gl_pathv = 0x60b170, gl_offs = 0, 
          gl_flags = 256, gl_closedir = 0x0, gl_readdir = 0x0, 
          gl_opendir = 0x0, gl_lstat = 0x0, gl_stat = 0x0}
        i = <optimized out>
#5  0x0000000000401211 in main (argc=<optimized out>, argv=<optimized out>)
    at toml_tap.c:213
No locals.
(gdb) 
```
