### ISSUE TITLE
some BurntSushi invalid input files parse without error

### ISSUE THREAD

**Issue by garlick** [cktan/tomlc99#4]
The following "invalid" test input files are parsed without error from tomlc99:

datetime-malformed-no-leads.toml
```toml
no-leads = 1987-7-05T17:45:00Z
```

datetime-malformed-no-secs.toml
```toml
no-secs = 1987-07-05T17:45Z
```

datetime-malformed-no-t.toml
```toml
no-t = 1987-07-0517:45:00Z
```

datetime-malformed-with-milli.toml
```toml
with-milli = 1987-07-5T17:45:00.12Z
```

float-no-leading-zero.toml
```toml
answer = .12345
neganswer = -.12345
```

float-no-trailing-digits.toml
```toml
answer = 1.
neganswer = -1.
```
