### ISSUE TITLE
Mixed-type arrays not supported

### ISSUE THREAD

**Issue by edrd-f** [cktan/tomlc99#51]
First of all, thanks for this great library. I'm writing some Kotlin Native bindings for it and so far it's working really well.

I just had a minor issue when writing a test for mixed-type arrays. The library produces an `array type mismatch while processing array of values` error.

According to the [array spec](https://toml.io/en/v1.0.0#array), mixed-type arrays are allowed:

```toml
# Mixed-type arrays are allowed
numbers = [ 0.1, 0.2, 0.5, 1, 2, 5 ]
contributors = [
  "Foo Bar <foo@example.com>",
  { name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }
]
```

This has no impact on my application, as tables (or arrays of tables) work just fine, but it would be nice for supporting 100% of the spec.
