### ISSUE TITLE
toml_parse_file including outside quotes in value

### ISSUE THREAD

**Issue by chinarjoshi** [cktan/tomlc99#84]
When parsing a file like this:

```toml
[acronym]
aa = "acronym add"
ae = "acronym edit"

[git]
ga = "git add -A"
gC = "git commit"
gc = "git commit -m"
```

The values in the tables `acronym` and `git` still have the outer double quotes. Is there something I'm missing when parsing files? The following except is the code I'm running.

```c
FILE *fp = fopen(toml_fname, "r");
if (!fp)
    return 0;
char errbuf[128];
toml_table_t *t = toml_parse_file(fp, errbuf, sizeof(errbuf));
```
